version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DBUSER=si5_sacc
      - DBHOST=database
      - DBNAME=td_1
      - DBPW=dev_password
      - DBPORT=5432
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=si5_sacc
      - POSTGRES_DB=td_1
